companyblog/models.py
from companyblog import db, login_manager
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from datetime import datetime

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

class User(db.Model, UserMixin):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    profile_image = db.Column(db.String(64), null=False, default = 'default_profile.png')# will be a link to a user file 
    email = db.Column(db.String(64), unique=True, index=True) # index true allows you to make the column an index to connect to other tables
    username = db.Column(db.String(64), unique=True, index=True)
    password_hash = db.Column(db.String(128))

    posts = db.relationship('BlogPost', backref='author', lazy=True)

    def __init__(self,email,username,password):
        self.email = email
        self.username = username
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return f"Username { self.username }"  
    
      
class BlogPost(db.Model):
    
    users = db.relationship(User)

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)

    date = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    title = db.Column(db.String(140), nullable=False)
    text = db.Column(db.Text, nullable=False)

    def __init__(self,title,text,user_id):
        self.title = title
        self.text = text
        self.user_id = user_id

    def __repr__(self):
        return f"Post Id: {self.id} -- Date: {self.date} -- Title: {self.title}"

companyblog/users/forms.py
from flask_wtf import FlaskForm
from wtforms StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email, EqualTo
from wtforms import ValidationError
from flask_wtf.file import FileField, FileAllowed # to allow user to update their profile image

from flask_login import current_user
from companyblog.models import User

class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit - SubmitField('Log In')

class RegistrationForm(FLaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    username = StringField('UserName', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired(), EqualTo('pass_confirm', message='Passwords must match!')])
    pass_confirm = PasswordField('Confirm Password', validators=[DataRequired()])
    submit = SubmitField('Register')

    def check_email(self,field):
        # user model from import 
        if User.query.filter_by(email=field.data).first():
            raise ValidationError(' Your Email Has Already Been Registered')

    def check_username(self,field):
        # user model from import 
        if User.query.filter_by(username=field.data).first():
            raise ValidationError(' Your Username Has Already Been Registered')

class UpdateUserForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    username = StringField('UserName', validators=[DataRequired()])
    picture = FileField('Update Profile Picture', validators=[FileAllowed(['jpg','png'])])
    submit = SubmitField('Update')

    def check_email(self,field):
        # user model from import 
        if User.query.filter_by(email=field.data).first():
            raise ValidationError(' Your Email Has Already Been Registered')

    def check_username(self,field):
        # user model from import 
        if User.query.filter_by(username=field.data).first():
            raise ValidationError(' Your Username Has Already Been Registered')

companyblog/__init__.py
# companyblog/__init__.py
#connect blueprints and login manager 
# to organize app
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager

app = Flask(__name__)

###### DATABASE SETUP ########
basedir = os.path.abspath(os.path.dirname(__file__))
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///' + os.path.join(basedir,'data.sqlite')
app.config['SQLALCHEMY_TRACK_MODIFICATIONS']  = False

db = SQLAlchemy(app)
Migrate(app,db)

########## Login Configs ###########
login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = 'users.login'

from companyblog.core.views import core
from companyblog.users.views import users
from companyblog.error_pages.handlers import error_pages

app.register_blueprint(core)
app.register_blueprint(users)
app.register_blueprint(error_pages)

companyblog/core/views.py
#core/views.py
#home view and info view 

from flask import render_template, request, Blueprint
core = Blueprint('core', __name__)

@core.route('/')
def index():
    return render_template('index.html')


@core.route('/info')
def info():
    return render_template('info.html')

companyblog/users/views.py
from flask import render_template, url_for, redirect, flash, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from companyblog import db
from companyblog.models import User, BlogPost
from companyblog.users.forms import RegistrationForm, LoginForm, UpdateUserForm
from companyblog.users.picture_handler import add_profile_pic

users = Blueprint('users', __name__)

#register user
@users.route('/register', methods=['GET','POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_sumbit():
        user = User(email=form.email.data,
                 username=form.username.data,
                 password=form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('Thanks for Registration')
        return redirect(url_for('users.login'))
    return render_template('register.html', form=form)

#login user
@users.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_sumbit():
        user = User.query.filter_by(email=form.email.data).first()
        if user.check_password(form.password.data) and user is not None:
            login_user(user)
            flash('Login Success')

            next = request.args.get('next')#grab the page user was trying to access from the requests session so i can redirect them
            if next == None or not next[0]=='/'
                next = url_for('core.index')
            return redirect(next)
    return render_template('login.html', form=form)

#logout user
@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('core.index'))

#account(update UserForm)
@users.route('/account', methods=['GET','POST'])
@login_required
def account():
    form = UpdateUserForm()
    if form.validate_on_sumbit():
        #if they uploaded pic FileField
        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data,username)
            current_user.profile_image = pic
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('User Account Updated')
        return redirect(url_for('users.account'))

    #not submitting anything we get their current info from form
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    profile_image = url_for('static', filename='profile_pics/'+current_user.profile_image)
    return render_template('account.html', profile_image=profile_image, form=form)

#show all list of users blog post
@users.route('/<username>')
def user_posts(username):
    page = request.args.get('page',1,type=int)

companyblog/templates/account.html
{% extends 'base.html' %}

{% block content %}
    <div class="jumbotron">
        <div align="center">
            <h1>Welcome to the page for {{ current_user.username }}</h1>
            <img align="center" src="{{ url_for('static/filename='profile_pics/'+current_user.profile_image) }}">
        </div>
    </div>

    <div class="container">
        <form action="POST">
            <div class="form-group">
                {{ form.hidden_tag() }}
            </div>
            <div class="form-group">
                {{ form.username.label(class="form-group") }}
                {{ form.username(class="form-control") }}<br>
            </div>
            <div class="form-group">
                {{ form.email.label(class="form-group") }}
                {{ form.email(class="form-control") }}<br>
            </div>
            <div class="form-group">
                {{ form.picture.label(class="form-group") }}
                {{ form.picture(class="form-control") }}<br>
            </div>
            <div class="form-group">
                {{ form.submit((class="btn btn-primary") }}
            </div>
            
        </form>
    </div>
{% endblock content

companyblog/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    <title></title>

</head>
<body>

    <ul class="nav">
        <li class="nav-link"><a href=" {{ url_for('core.index') }}">Home</a></li>
        <li class="nav-link"><a href=" {{ url_for('core.info') }}">About</a></li>
        <li class="nav-link"><a href="#">Log Out</a></li>
        <li class="nav-link"><a href="#">Account</a></li>
        <li class="nav-link"><a href="#">Create Post</a></li>
        <li class="nav-link"><a href="#">Log In</a></li>
        <li class="nav-link"><a href="#">Register</a></li>
    </ul>

    <div class="container">
        {% block content %}

        {% endblock %}
        
    </div>

</body>
</html>

companyblog/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <div class="jumbotron">
        <h1>Company Blog</h1>
    </div>
{% endblock %}

companyblog/templates/info.html
{% extends 'base.html' %}

{% block content %}
    <div class="jumbotron">
        <h1>Info about our company.</h1>
        <p>Lorem ipsum dolor sit amet, 
            consectetur adipisicing elit. Deserunt, aperiam esse voluptatum reprehenderit sed earum, 
            explicabo cum vero ex aliquam ad perferendis amet,
            quia delectus corporis voluptates sapiente quos repudiandae.</p>
    </div>
{% endblock %}

companyblog/templates/login.html
{% extends 'base.html' %}

{% block content %}
    <form action="POST">
        {{ form.hidden_tag() }}
        {{ form.email.label }}{{ form.email }}<br>
        {{ form.email.password }}{{ form.password}}<br>
        {{ form.submit() }}
    </form>
{% endblock content

companyblog/templates/register.html
{% extends 'base.html' %}

{% block content %}
    <form action="POST">
        {{ form.hidden_tag() }}
        {{ form.email.label }}{{ form.email }}<br>
        {{ form.email.username }}{{ form.username }}<br>
        {{ form.email.password }}{{ form.password}}<br>
        {{ form.email.pass_confirm }}{{ form.pass_confirm }}<br>
        {{ form.submit() }}
        
    </form>
{% endblock content